### ISSUE TITLE
Getting iOS build error after updating to 6.3.2

### ISSUE THREAD

**Issue by jonathanahern** [AppsFlyerSDK/appsflyer-unity-plugin#105]
I'm having trouble updating to 6.3.2 from 6.2.4. I'm updating because I'm having trouble getting SKADNet to work. When I try to build in Xcode I get this error:
"Implicit declaration of function 'GTMBridgeAssertValidSelector' is invalid in C99".
<img width="633" alt="Screen Shot 2021-06-26 at 12 28 23 PM" src="https://user-images.githubusercontent.com/22061385/123519588-406a6200-d67a-11eb-9934-0f9727b995f7.png">

Part of the problem might be that my Appsflyer files are in a different location so I manually delete the old files before uploading. I also remove the assembly files so my scripts can find Appsflyer for events, but I imagine there's a better way to do this. I'm also using Firebase. 

Let me know if you need more information.

Thanks,
Jonathan

**Comment by jonathanahern** [comment]
Sorry, this seems to be unrelated to Appsflyer. My old builds that were working give me the same error.
