### ISSUE TITLE
AppsFlyer 6.3.2 + Unity 2020.3.14f1 + Android or iOS

### ISSUE THREAD

**Issue by pwhitney** [AppsFlyerSDK/appsflyer-unity-plugin#118]
In Unity 2019, we were having successful builds using AppsFlyer Unity Plugin 6.3.+. In Unity 2020.3.14f1, android builds are always failing:

```
Error: Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

/_BuildPath_/android/Temp/gradleOut/unityLibrary/src/main/java/com/appsflyer/GetDeepLinkingActivity.java:28: error: cannot find symbol
 		AppsFlyerLib.getInstance().setDeepLinkData(getIntent());
 		                          ^
   symbol:   method setDeepLinkData(Intent)
   location: class AppsFlyerLib
```

iOS build are successfully built but crash in game when triggering: `AppsFlyer.sendEvent(AFInAppEvents.COMPLETE_REGISTRATION, new Dictionary<string, string>());`

All information for migration (https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/docs/MigrationGuide.md#sameapi) has been followed with no luck. Any help would be greatly appreciated.

Thanks!

**Comment by ge-af** [comment]
Hi @pwhitney 

It looks like you are still have some "leftovers" from the migration process that should be removed or that your project was not cleaned and re-built. 
Please have a look at this note [here](https://github.com/AppsFlyerSDK/appsflyer-unity-plugin/blob/master/docs/MigrationGuide.md#-update-deeplink-logic) 

_Unity v5 does not include com.appsflyer.GetDeepLinkingActivity.
This was used in Unity v4 as a workaround for deeplinking.
If you are using this class for deeplinking, then make sure to remove the GetDeepLinkingActivity from the AndroidManifest.xml file._

**Comment by Dariofdz** [comment]
Hi there!
I have the same error.

In Unity 2019 it was working perfectly. I am migrating the project to Unity 2020 and now on **Android it works perfectly** but on **iOS** when invoking the **AppsFlyer.sendEvent (...)** method, it **crashes**.


Unity version: Unity 2020.3.14f1
AppsFlyerPluginVersion: 6.2.61
iosPod, AppsFlyerFramework version: 6.2.6

Thanks!

**Comment by ge-af** [comment]
Hi @Dariofdz and @pwhitney, 

Can you please provide and share a full iOS stack trace of the crash?

**Comment by Dariofdz** [comment]
In the stack trace it seems that the "_eventData_" passed as a parameter is empty, but that seems very difficult. 

The call is as follows:
```csharp
Dictionary <string, string> eventValue = new Dictionary <string, string> (); 
eventValue.Add ("username", "Dario"); // HardCode testing
TrackingService.Instance.TrackEvent ("unity_complete_login", eventValue);
```
Error stack  trace: 

> Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000020
VM Region Info: 0x20 is not in any region.  Bytes before following region: 4331290592
      REGION TYPE                 START - END      [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->
      __TEXT                   1022a4000-1022a8000 [   16K] r-x/r-x SM=COW  ...p/Mundijuegos
Triggered by Thread:  0
Thread 0 name:
Thread 0 Crashed:
0   libsystem_platform.dylib      	0x00000001e129e724 _platform_strlen + 4
1   Foundation                    	0x0000000199c1cc84 +[NSString stringWithUTF8String:] + 40 (NSString.m:197)
2   UnityFramework                	0x00000001025f0408 stringFromChar(char const*) + 36 (AFUnityUtils.mm:16)
3   UnityFramework                	0x00000001025f1118 _afSendEvent + 40 (AppsFlyeriOSWrapper.mm:104)
4   UnityFramework                	0x0000000103b8847c AppsFlyeriOS__afSendEvent_m8CD9242D1E3952CA68F69F4266BF123B1D3C7158 + 48 (AppocalypseSDKAsm2.cpp:32683)
5   UnityFramework                	0x00000001041b45c4 InterfaceActionInvoker2<String_t*, Dictionary_2_tDE3227CA5E7A32F5070BD24C69F42204A3ADE9D5*>::Invoke(unsigned short, Il2CppClass*, Il2CppObject*, String_t*, Dictionary_2_tDE3227CA5E7A32F5070BD24C69F... + 92 (AppocalypseSDKAsm74.cpp:76)
6   UnityFramework                	0x00000001041b45c4 TrackingService_TrackEvent_m380CEF0D8A1A093D54B1F24BFA71450D65011F35 + 248 (AppocalypseSDKAsm74.cpp:25203)
7   UnityFramework                	0x00000001047f2204 MobileLoginController_OnLogin_m9FDA692BD8524EC384F701B8F8D89C9567BB0121 + 924 (Assembly-CSharp28.cpp:43538)
8   UnityFramework                	0x0000000104d24520 Action_1_Invoke_m587509C88BB83721D7918D89DF07606BB752D744_gshared + 148 (Generics1.cpp:0)
9   UnityFramework                	0x00000001042f301c Action_1_Invoke_m84EFDF7CFEE4EA329CE3A3BB312AA72CC98F77FE(Action_1_t36292198BE5ABC02C974204803AE66BAF44A58CD*, OnLoginEvent_tA9862F48C211EB76114FD3EF2F73A0F0F585A3B5*, MethodInfo const*) + 4 (AppocalypseSDKAsm84.cpp:50618)
10  UnityFramework                	0x00000001042f301c U3CLoginU3Ed__1_MoveNext_m4D7CEF21F634682E10FB2761BEE8CBA6801AD100 + 900 (AppocalypseSDKAsm84.cpp:80228)
11  UnityFramework                	0x000000010580da48 ContextCallback_Invoke_mF4F8496213E8F0925947DD8994A477AE2E54EFDF + 408
12  UnityFramework                	0x00000001058af460 ExecutionContext_RunInternal_mC5D58D6EDE270B4CDA05181E9064E040D6692B2B + 364 (mscorlib7.cpp:25530)
13  UnityFramework                	0x0000000105833850 MoveNextRunner_Run_mF9986F86D538F629861F62DD912B18CC58980D8B + 260 (mscorlib21.cpp:22687)
14  UnityFramework                	0x00000001056f9d3c Action_Invoke_m3FFA5BE3D64F0FF8E1E1CB6F953913FADB5EB89E + 276
15  UnityFramework                	0x000000010578f130 SendOrPostCallback_Invoke_m352534ED0E61440A793944CC44809F666BBC1461 + 148 (mscorlib15.cpp:0)
16  UnityFramework                	0x0000000105643504 WorkRequest_Invoke_m1C292B7297918C5F2DBE70971895FE8D5C33AA20 + 36 (UnityEngine.CoreModule1.cpp:50060)
17  UnityFramework                	0x0000000105643474 UnitySynchronizationContext_Exec_mC89E49BFB922E69AAE753887480031A142016F81 + 284 (UnityEngine.CoreModule1.cpp:41945)
18  UnityFramework                	0x00000001025a3a4c RuntimeInvoker_FalseVoid_t700C6383A2A510C2CF4DD86DABD5CA9FF70ADAC5(void (*)(), MethodInfo const*, void*, void**) + 20 (Il2CppInvokerTable.cpp:97157)
19  UnityFramework                	0x000000010388b9f4 il2cpp::vm::Runtime::Invoke(MethodInfo const*, void*, void**, Il2CppException**) + 116 (Runtime.cpp:568)
20  UnityFramework                	0x000000010315bba0 scripting_method_invoke(ScriptingMethodPtr, ScriptingObjectPtr, ScriptingArguments&, ScriptingExceptionPtr*, bool) + 124 (ScriptingApi_Il2Cpp.cpp:292)
21  UnityFramework                	0x0000000103167430 ScriptingInvocation::Invoke(ScriptingExceptionPtr*, bool) + 120 (ScriptingInvocation.cpp:273)
22  UnityFramework                	0x0000000102d44748 Scripting::UnityEngine::UnitySynchronizationContextProxy::ExecuteTasks(ScriptingExceptionPtr*) + 80 (CoreScriptingClasses.cpp:0)
23  UnityFramework                	0x000000010308ff90 ExecutePlayerLoop(NativePlayerLoopSystem*) + 100 (PlayerLoop.cpp:383)
24  UnityFramework                	0x000000010308ffd0 ExecutePlayerLoop(NativePlayerLoopSystem*) + 164 (PlayerLoop.cpp:404)
25  UnityFramework                	0x000000010309029c PlayerLoop() + 272 (PlayerLoop.cpp:504)
26  UnityFramework                	0x0000000103427fbc UnityPlayerLoopImpl(bool) + 112 (LibEntryPoint.mm:329)
27  UnityFramework                	0x000000010246434c UnityRepaint + 12 (UnityAppController+Rendering.mm:230)
28  UnityFramework                	0x000000010246434c -[UnityAppController(Rendering) repaint] + 108 (UnityAppController+Rendering.mm:90)
29  UnityFramework                	0x00000001024642b4 -[UnityAppController(Rendering) repaintDisplayLink] + 108 (UnityAppController+Rendering.mm:71)
30  QuartzCore                    	0x000000019bbc1640 CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) + 660 (CADisplay.mm:2635)
31  QuartzCore                    	0x000000019bc93a20 display_timer_callback(__CFMachPort*, void*, long, void*) + 276 (CADisplayTimer.cpp:166)
32  CoreFoundation                	0x00000001989e6b54 __CFMachPortPerform + 172 (CFMachPort.c:537)
33  CoreFoundation                	0x0000000198a0a420 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 56 (CFRunLoop.c:1991)
34  CoreFoundation                	0x0000000198a09834 __CFRunLoopDoSource1 + 588 (CFRunLoop.c:2131)
35  CoreFoundation                	0x0000000198a039f4 __CFRunLoopRun + 2332 (CFRunLoop.c:3146)
36  CoreFoundation                	0x0000000198a02ba0 CFRunLoopRunSpecific + 572 (CFRunLoop.c:3242)
37  GraphicsServices              	0x00000001af768598 GSEventRunModal + 160 (GSEvent.c:2259)
38  UIKitCore                     	0x000000019b2f42f4 -[UIApplication _run] + 1052 (UIApplication.m:3253)
39  UIKitCore                     	0x000000019b2f9874 UIApplicationMain + 164 (UIApplication.m:4707)
40  UnityFramework                	0x0000000102463d84 -[UnityFramework runUIApplicationMainWithArgc:argv:] + 108 (main.mm:96)
41  Mundijuegos                   	0x00000001022abd54 main + 68 (main.mm:26)
42  libdyld.dylib                 	0x00000001986e1568 start + 4

**Comment by ge-af** [comment]
This code snippet doesn't resemble AppsFlyer's SDK code or invocation: 

```
Dictionary <string, string> eventValue = new Dictionary <string, string> (); 
eventValue.Add ("username", "Dario"); // HardCode testing
TrackingService.Instance.TrackEvent ("unity_complete_login", eventValue);
```

Please open a Support ticket at support@appsflyer.com with all the relevant information and we will more than glad to supply on the assistance needed.

**Comment by af-margot** [comment]
Hi, 
I’m closing this issue because it has been inactive for a while.
Please reopen if you still encounter this issue :)

Thank you!
